wesql/wescale

doc/developer/Use FailPoint Injection In WeScale.md
=> Update Use FailPoint Injection In WeScale.md

go/test/endtoend/tabletmanager/tablegc/tablegc_test.go, go/vt/schema/online_ddl.go, go/vt/schema/online_ddl_utils.go, go/vt/schema/tableSchemaAndName.go, go/vt/schema/tablegc.go, go/vt/schema/tablegc_test.go, go/vt/vttablet/onlineddl/executor.go, go/vt/vttablet/tabletserver/gc/tablegc.go, go/vt/vttablet/tabletserver/gc/tablegc_test.go, go/vt/vttablet/tabletserver/tabletenv/config.go, go/vt/vttablet/tabletserver/tabletserver.go
fix https://github.com/wesql/wesql-scale/issues/269
=> feat: support tablegc

go/vt/vttablet/onlineddl/executor.go
=> fix: modify DbaWithDB to DbaConnector

README.md, doc/blogs/Execution Process of DROP TABLE in OnlineDDL Mode.md
fix https://github.com/wesql/wescale/issues/289
=> feat: add doc for drop table

doc/toturial/03-Read-Write-Split & LoadBalancer.md, go/vt/vtgate/vcursor_impl.go
Specific description is in #309 
#309 
The pseudocode is as follows：
```
if udv != nil {
if is not in read only transaction {
switch = udv
udv = nil
}
}
```
Note that when using `set` SQL to set user variables, the value defined by the user will only appear in the `UserDefinedVariables` of the current session after this `set` SQL is executed. This means that only the next SQL statement after `set` SQL can use the value defined by the user.
The code can achieve the expected effect in the following scenarios.
```
user turn on/off switch --- 1
other SQLs...
------------------ use the the switch value set in 1 until commit
start read only tx
other SQLs...
user turn on/off switch --- 2
other SQLs...
user turn on/off switch --- 3
other SQLs...
commit …
```
=> feat: add read only tx routing switch

.checklicenseignore, .github/workflows/cluster_endtoend_onlineddl_vrepl_stress.yml, .github/workflows/cluster_endtoend_onlineddl_vrepl_stress_mysql57.yml, .github/workflows/cluster_endtoend_onlineddl_vrepl_stress_suite.yml, .github/workflows/cluster_endtoend_onlineddl_vrepl_stress_suite_mysql57.yml, .github/workflows/cluster_endtoend_onlineddl_vrepl_suite.yml, .github/workflows/cluster_endtoend_onlineddl_vrepl_suite_mysql57.yml, Makefile, go/test/endtoend/onlineddl/vrepl_stress/onlineddl_vrepl_mini_stress_test.go, go/test/endtoend/onlineddl/vrepl_stress_suite/onlineddl_vrepl_stress_suite_test.go, go/test/endtoend/onlineddl/vrepl_suite/onlineddl_vrepl_suite_test.go, go/test/endtoend/onlineddl/vrepl_suite/testdata/fail-syntax-error/expect_query_failure, go/test/endtoend/onlineddl/vtgate_util.go, go/vt/vttablet/onlineddl/executor.go, tools/wesql_onlineddl_vrepl_stress.sh, tools/wesql_onlineddl_vrepl_stress_suite.sh, tools/wesql_onlineddl_vrepl_suite.sh
add vrepl_suite and vrepl_stress_suite testcase
=> test: add vrepl_suite and vrepl_stress_suite testcase

go/test/endtoend/onlineddl/scheduler/onlineddl_scheduler_test.go
=> test: add instantDDL_e2e_testcase

examples/workflow/movetables/run.sh, go/vt/vtctl/workflow/traffic_switcher.go
fix https://github.com/wesql/wescale/issues/365
=> fix: primary dbname

go/vt/schemadiff/table.go, go/vt/wrangler/branch.go
=> feat: apply diffEntries and compare with target schema

docker/wesqlscale/local/install_dependencies.sh, go/vt/vtgate/evalengine/func.go
=> test: fix mysql-tester env

doc/toturial/08-Branch.md, go/vt/wrangler/branch.go
=> docs: add branch tutorial

go/vt/vtgate/vtgate.go
=> fix: add pflag params for rdonly txn routing and sql execution vttablet

README.md
Add a tutorial on branches to the README file.
=> docs: add branch tutorial in readme

go/vt/vttablet/jobcontroller/batch_sql_related.go, go/vt/vttablet/jobcontroller/controller.go, go/vt/vttablet/jobcontroller/running_period_time.go, go/vt/vttablet/jobcontroller/throttle.go, go/vt/vttablet/jobcontroller/util.go
clean up and improve the comments in non-transactional dml
=> docs: clean up and improve the comments in non-transactional dml

go/viperutil/config_reloader_test.go, go/viperutil/test/vtgate_test_modify.cnf, go/viperutil/viper_config.go, go/viperutil/vtgate_handlers.go, go/viperutil/vtgate_handlers_test.go, go/viperutil/vttablet_handlers.go, go/vt/vtgate/plugin_mysql_server.go
related this issue https://github.com/apecloud/apecloud/issues/1913. Wescala should have the capability to dynamically load TLS configuration parameters.
=> feat: Dynamically load TLS configuration params

go/test/endtoend/wesql/auth/tableacl_test.go, go/vt/vttablet/tabletserver/planbuilder/permission.go
=> fix: fix tableACL database check

.checklicenseignore, examples/common/scripts/vtgate-up.sh, examples/common/scripts/vttablet-up.sh, examples/mysql/vtgate.cnf, examples/mysql/vttablet.cnf
=> 474 enhancement request use config files to start cluster in examples

doc/toturial/00-Deploy&Debug.md
I noticed a small problem while reading the tutorial docs and made this correction.
Hopefully this will be my first little contribution to the community.
=> docs: fix shutdown command in 00-Deploy&Debug.md

examples/mysql/vtgate.cnf, go/test/endtoend/wesql/queries/main_test.go, go/vt/vttablet/onlineddl/executor.go, go/vt/vttablet/tabletserver/action.go, go/vt/vttablet/tabletserver/action_builtin.go, go/vt/vttablet/tabletserver/action_builtin_test.go, go/vt/vttablet/tabletserver/action_factory.go, go/vt/vttablet/tabletserver/action_factory_test.go, go/vt/vttablet/tabletserver/query_executor.go, go/vt/vttablet/tabletserver/rules/rules.go
=> support SQL Concurrency Control

go/vt/vttablet/tabletserver/query_engine.go
=> fix: remove sql hash for query_template

go/vt/vttablet/tabletserver/action_builtin.go
=> chore: polish code for wescale filter

README.md, doc/toturial/09-Non-Transactional DML.md, doc/toturial/10-Show Tablets Query Plans.md
=> doc: add show tables query plans doc

go/vt/vtgate/executor.go, go/vt/vttablet/customrule/config.go, go/vt/vttablet/customrule/databasecustomrule/databasecustomrule.go, go/vt/vttablet/tabletserver/common_query_functions.go
1.fix wescale filter bug: change from `Timer` to `Ticker`.
2.notify follower tablets to reload filters from database when executing filter dml cmd.
=> fix:fix wescale filter ticker bug

examples/wesql/start_cluster_docker.sh
=> fix: fix image name of start_cluster_docker.sh

go/vt/sqlparser/table_collector.go, go/vt/sqlparser/table_collector_test.go, go/vt/vtgate/read_write_splitter.go, go/vt/vttablet/tabletserver/planbuilder/permission_test.go, go/vt/vttablet/tabletserver/planbuilder/plan_test.go, go/vt/vttablet/tabletserver/planbuilder/testdata/ddl_cases.txt, go/vt/vttablet/tabletserver/planbuilder/testdata/exec_cases.txt, go/vt/vttablet/tabletserver/planbuilder/testdata/stream_cases.txt
=> fix: add table collector

README.md, doc/toturial/12-Filters.md
=> docs: add filter doc

go/vt/vttablet/tabletserver/action_builtin.go, go/vt/vttablet/tabletserver/rules/rules.go, go/vt/vttablet/tabletserver/wescale_filter_request_handler.go
=> fix: check if wasm plugin binary valid when creating filter

go/vt/vttablet/tabletserver/action_builtin.go, go/vt/vttablet/tabletserver/wasm_plugin_host_functions.go, go/vt/vttablet/tabletserver/wasm_plugin_types.go, go/vt/vttablet/tabletserver/wasm_plugin_wazero.go
=> feat: support query result in RunAfterExecution

doc/blogs/Dive into Read-Write-Splitting of WeScale.md, doc/blogs/Execution Process of DROP TABLE in OnlineDDL Mode.md, doc/blogs/Introduction To WeScale.md, doc/blogs/Performance Comparison WeScale vs MySQL.md, doc/design/00000000_template.md, doc/design/20230414_ReadAfterWrite.md, doc/design/20230609_CompressGtidSets.md, doc/design/20230809_LeastBusyConnectionLoadBalancePolicy.md, doc/design/20231113_OnlineDDLScheduler.md, doc/design/20231113_TheLifecycleofAlterTableStatements.md, doc/design/20231113_Vreplication.md, doc/design/20240514_Filters.md, doc/design/20240531_WasmPlugin.md, doc/developer/Use FailPoint Injection In WeScale.md, doc/toturial/00-Deploy&Debug.md, doc/toturial/01-Architecture.md, doc/toturial/02-Life of A Query.md, doc/toturial/03-Read-Write-Split & LoadBalancer.md, doc/toturial/04-Read-After-Write-Consistency.md, doc/toturial/05-Transparent Failover.md, doc/toturial/06-Authentication&Authorization.md, doc/toturial/07-OnlineDDL-User-Guide.md, doc/toturial/08-Branch.md, doc/toturial/09-Non-Transactional DML.md, doc/toturial/10-Show Tablets Query Plans.md, doc/toturial/11-Getting-Started-with-Kubernetes.md, doc/toturial/12-Filters.md, doc/toturial/13-Write-a-Wasm-Plugin-In-WeScale.md
=> docs: add title

examples/cdc/mirror/go.mod, examples/cdc/mirror/go.sum, examples/cdc/vector/go.mod, examples/cdc/vector/go.sum
fix: update cdc dependency version; go mod tidy
=> fix: update cdc dependency version

docker/wesqlscale/Dockerfile, docker/wesqlscale/Dockerfile.release
=> feat: fix dockerfile

go/vt/wrangler/branch.go
=> fix log message

.github/workflows/release-image.yml
=> chore: matrix release image

.github/workflows/cherry-pick.yaml, .github/workflows/cherry-pick.yaml.bak
=> Add cherry pick.yaml

go/vt/failpointkey/failpoint_keys.go, go/vt/sidecardb/sidecardb.go, go/vt/vttablet/tabletserver/schema/engine.go
=> feat: fix sidecardb creation on vttablet Init

go/viperutil/vtgate_handlers.go, go/vt/vtgate/autoscale/controller.go, go/vt/vtgate/autoscale/decision_maker.go, go/vt/vtgate/autoscale/instruction_executor.go, go/vt/vtgate/autoscale/metrics_collector.go, go/vt/wrangler/branch.go
=> chore: fix branch output

examples/wesql-server/conf/vtgate.cnf, examples/wesql-server/init_single_node_cluster.sh, examples/wesql-server/vtgate.sh
=> Update init single node cluster

.github/workflows/pick-and-release.yaml
=> feat: add auto tag and release workflow

go/test/endtoend/wesql/queries/routing_test.go, go/vt/vtgate/tabletgateway.go, go/vt/vttablet/tabletserver/role/listener.go, go/vt/vttablet/tabletserver/role/mysql_probe.go
=> fix: fix bug in mysql probe

go/viperutil/test/vttablet.cnf, go/viperutil/test/vttablet_test_modify.cnf, go/viperutil/vttablet_handlers.go, go/viperutil/vttablet_handlers_test.go, go/vt/vttablet/jobcontroller/controller.go, go/vt/vttablet/jobcontroller/param_setting.go, go/vt/vttablet/jobcontroller/util.go, go/vt/vttablet/tabletserver/tabletserver.go
=> fix: merge dml job controller connection pool

examples/connection-pool/go.sum, go/vt/servenv/servenv.go, go/vt/vttls/vttls.go
=> feat: support configurable server side ssl ca check

go/vt/vtgate/branch/branch_meta.go, go/vt/vtgate/branch/branch_service.go, go/vt/vtgate/branch/common_mysql_service.go, go/vt/vtgate/branch/target_mysql_service.go, go/vt/vtgate/branch/target_mysql_service_test.go, go/vt/vtgate/branch/test_util.go, go/vt/vtgate/engine/branch_primitive.go
=> Branch2 fix bugs

.github/workflows/branch_example.yml, doc-chinese/toturial/08-Branch.md, doc/toturial/08-Branch.md
=> Update branch docs
